name: Try to Build

on:
  workflow_dispatch:
  push:

jobs:
  try-build:
    name: Try to Build on ${{ matrix.os }} with Swift ${{ matrix.swift-version }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        swift-version: ["5.7.1"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.swift-format.outputs.commitSHA }}
      - name: Install Swift ${{ matrix.swift-version }} on macOS/Linux
        if: ${{ runner.os != 'Windows' }}
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Install Swift ${{ matrix.swift-version }} on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          Install-Binary -Url "https://download.swift.org/swift-${{ matrix.swift-version }}-release/windows10/swift-${{ matrix.swift-version }}-RELEASE/swift-${{ matrix.swift-version }}-RELEASE-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
          Add-Content $env:GITHUB_PATH "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin"
          Add-Content $env:GITHUB_PATH "C:\Program Files\swift\runtime-development\usr\bin"
          Add-Content $env:GITHUB_PATH "C:\Program Files\swift\icu-69.1\usr\bin"
          Add-Content $env:GITHUB_ENV "SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk"
          Add-Content $env:GITHUB_ENV "DEVELOPER_DIR=C:\Library\Developer"
      - name: Enable MS Developer Command Prompt
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Builds fine with NOT_BROKEN defined
        run: |
          swift build -DNOT_BROKEN
      - name: Build breaks
        run: |
          swift build --use-integrated-swift-driver